FROM python:3
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
ENV TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
ENV TWILIO_PERSONAL_PHONE_NUMBER=${TWILIO_PERSONAL_PHONE_NUMBER}
ENV TWILIO_ACCOUNT_PHONE_NUMBER=${TWILIO_ACCOUNT_PHONE_NUMBER}
CMD ["python", "-u", "main.py"]
