version: "3.0"
services:
  main:
    build: .
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PERSONAL_PHONE_NUMBER=${TWILIO_PERSONAL_PHONE_NUMBER}
      - TWILIO_ACCOUNT_PHONE_NUMBER=${TWILIO_ACCOUNT_PHONE_NUMBER}
