newegg:
  url: https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-10g-gaming/p/N82E16814126453?Item=N82E16814126453
  indicator: <button class="btn btn-primary btn-wide" title="Add ASUS TUF Gaming NVIDIA GeForce RTX 3080 TUF-RTX3080-10G-GAMING Video Card to cart">Add to cart <i class="fas fa-caret-right"></i></button>

bestbuy:
  url: https://www.bestbuy.com/site/nvidia-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-graphics-card-titanium-and-black/6429440.p?skuId=6429440
  indicator: <div><button class="btn btn-primary btn-lg btn-block btn-leading-ficon add-to-cart-button" type="button" style="padding:0 8px"><svg aria-hidden="true" role="img" viewBox="0 0 100 100" style="width:16px;height:16px;margin-bottom:-2px;margin-right:9px;fill:currentColor"><use href="/~assets/bby/_img/int/plsvgdef-frontend/svg/cart.svg#cart" xlink:href="/~assets/bby/_img/int/plsvgdef-frontend/svg/cart.svg#cart"></use></svg>Add to Cart</button></div>

#newegg_test:
#  url: https://www.newegg.com/g-skill-32gb-288-pin-ddr4-sdram/p/N82E16820232091?Item=N82E16820232091&quicklink=true
#  indicator: <button class="btn btn-primary btn-wide" title="Add G.SKILL Ripjaws V Series 32GB (2 x 16GB) 288-Pin DDR4 SDRAM DDR4 3200 (PC4 25600) Desktop Memory Model F4-3200C16D-32GVK to cart">Add to cart <i class="fas fa-caret-right"></i></button>
#
#bestbuy_test:
#  url: https://www.bestbuy.com/site/samsung-75-class-q60t-series-led-4k-uhd-smart-tizen-tv/6401711.p?skuId=6401711
#  indicator: </svg>Add to Cart</button>

